account_id = "757771412865"
region = "eu-west-2"
data_stack_name = "fpl-relay-data"
application_stack_name = "fpl-relay-app"
alert_email = "nixprivacy@pm.me"
collector_source_user_name = "fpl-relay-nas-source"
payload_prefix = "payloads/v1"
migration_parameter_prefix = "/fpl-data-relay/production/infrastructure-migrations"
collector_image = "ghcr.io/danballance/fpl-data-relay-collector"
