"""Typed entity snapshots, field diffs, and change-feed records."""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator

from fpl_data_relay.domain.types import JsonValue


class IngestionSourceKey(StrEnum):
    """Upstream source identifiers used for latest ingestion metadata."""

    BOOTSTRAP = "bootstrap-static"
    FIXTURES = "fixtures"
    CURRENT_FIXTURES = "fixtures-current-event"
    EVENT_STATUS = "event-status"
    EVENT_LIVE = "event-live"


class EntityFamily(StrEnum):
    """Normalised entity families exposed by change events."""

    EVENTS = "events"
    PHASES = "phases"
    TEAMS = "teams"
    ELEMENT_TYPES = "element_types"
    ELEMENT_STATS = "element_stats"
    ELEMENTS = "elements"
    FIXTURES = "fixtures"
    EVENT_STATUS = "event_status"
    EVENT_LIVE = "event_live"


class ChangeKind(StrEnum):
    """Supported entity-level operations."""

    CREATED = "created"
    UPDATED = "updated"
    DELETED = "deleted"


EVENT_NAMES: dict[EntityFamily, str] = {
    EntityFamily.EVENTS: "events.updated",
    EntityFamily.PHASES: "phases.updated",
    EntityFamily.TEAMS: "teams.updated",
    EntityFamily.ELEMENT_TYPES: "element_types.updated",
    EntityFamily.ELEMENT_STATS: "element_stats.updated",
    EntityFamily.ELEMENTS: "elements.updated",
    EntityFamily.FIXTURES: "fixtures.updated",
    EntityFamily.EVENT_STATUS: "event_status.updated",
    EntityFamily.EVENT_LIVE: "event_live.updated",
}


class IngestionMetadata(BaseModel):
    """Metadata for one upstream source fetch."""

    model_config = ConfigDict(frozen=True)

    season_id: str
    source_key: IngestionSourceKey
    event_id: int | None
    payload_hash: str
    fetched_at: datetime
    checked_at: datetime

    @field_validator("payload_hash")
    @classmethod
    def payload_hash_must_be_sha256(cls, value: str) -> str:
        """Validate that stored payload hashes look like SHA-256 digests."""
        if len(value) != 64:
            raise ValueError("payload_hash must be a SHA-256 hex digest.")
        return value


class ChangeValue(BaseModel):
    """One side of a field change, distinguishing absence from JSON null."""

    model_config = ConfigDict(frozen=True)

    present: bool
    value: JsonValue


class FieldChange(BaseModel):
    """Before and after values for one top-level entity field."""

    model_config = ConfigDict(frozen=True)

    field: str
    before: ChangeValue
    after: ChangeValue


class EntitySnapshot(BaseModel):
    """Canonical current representation used for entity-level comparisons."""

    model_config = ConfigDict(frozen=True)

    entity_key: str
    entity_label: str
    data: dict[str, JsonValue]


class EntityChangeDraft(BaseModel):
    """Unpersisted entity change generated by the pure diff engine."""

    model_config = ConfigDict(frozen=True)

    entity_key: str
    entity_label: str
    kind: ChangeKind
    fields: list[FieldChange]


class EntityFamilyDiff(BaseModel):
    """Changes found for one entity family."""

    model_config = ConfigDict(frozen=True)

    baseline: bool
    changes: list[EntityChangeDraft] = Field(default_factory=list)

    @property
    def created_count(self) -> int:
        """Return the number of newly created entities."""
        return sum(change.kind is ChangeKind.CREATED for change in self.changes)

    @property
    def updated_count(self) -> int:
        """Return the number of updated entities."""
        return sum(change.kind is ChangeKind.UPDATED for change in self.changes)

    @property
    def deleted_count(self) -> int:
        """Return the number of deleted entities."""
        return sum(change.kind is ChangeKind.DELETED for change in self.changes)


class ChangeEvent(BaseModel):
    """Summary of accurate entity changes within one normalised family."""

    model_config = ConfigDict(frozen=True)

    id: int
    season_id: str
    entity_family: EntityFamily
    event_name: str
    source_key: IngestionSourceKey
    source_event_id: int | None
    payload_hash: str
    created_count: int
    updated_count: int
    deleted_count: int
    fetched_at: datetime
    created_at: datetime


class EntityChange(BaseModel):
    """Persisted field-level changes for one entity."""

    model_config = ConfigDict(frozen=True)

    id: int
    change_event_id: int
    entity_key: str
    entity_label: str
    kind: ChangeKind
    fields: list[FieldChange]
    created_at: datetime


class IngestionSourceStatus(BaseModel):
    """Latest successful check and change timestamps for one source."""

    model_config = ConfigDict(frozen=True)

    season_id: str
    source_key: IngestionSourceKey
    event_id: int | None
    payload_hash: str
    fetched_at: datetime
    checked_at: datetime
    last_changed_at: datetime | None


class UpsertOutcome(BaseModel):
    """Result of attempting to upsert one source payload."""

    model_config = ConfigDict(frozen=True)

    changed: bool
    change_events: list[ChangeEvent] = Field(default_factory=list)


def diff_entity_snapshots(
    *,
    previous: list[EntitySnapshot],
    current: list[EntitySnapshot],
    authoritative: bool,
    baseline: bool,
) -> EntityFamilyDiff:
    """Compare canonical snapshots without coupling the domain to persistence."""
    previous_by_key = snapshots_by_key(snapshots=previous)
    current_by_key = snapshots_by_key(snapshots=current)
    changes: list[EntityChangeDraft] = []
    for entity_key in sorted(previous_by_key.keys() | current_by_key.keys()):
        before = previous_by_key.get(entity_key)
        after = current_by_key.get(entity_key)
        if before is None and after is not None:
            if not baseline:
                changes.append(
                    entity_change_for_create(snapshot=after),
                )
            continue
        if after is None and before is not None:
            if authoritative and not baseline:
                changes.append(
                    entity_change_for_delete(snapshot=before),
                )
            continue
        if before is None or after is None:
            raise RuntimeError("Entity diff reached an impossible snapshot state.")
        fields = changed_fields(before=before.data, after=after.data)
        if fields and not baseline:
            changes.append(
                EntityChangeDraft(
                    entity_key=entity_key,
                    entity_label=after.entity_label,
                    kind=ChangeKind.UPDATED,
                    fields=fields,
                ),
            )
    return EntityFamilyDiff(baseline=baseline, changes=changes)


def entity_keys_to_upsert(
    *,
    diff: EntityFamilyDiff,
    current: list[EntitySnapshot],
) -> set[str]:
    """Return current entity keys that require normalized persistence."""
    current_by_key = snapshots_by_key(snapshots=current)
    if diff.baseline:
        return set(current_by_key)
    keys = {
        change.entity_key
        for change in diff.changes
        if change.kind in {ChangeKind.CREATED, ChangeKind.UPDATED}
    }
    missing = keys - current_by_key.keys()
    if missing:
        raise RuntimeError(
            "Entity diff selected keys absent from the current snapshot: "
            f"{sorted(missing)!r}.",
        )
    return keys


def snapshots_by_key(
    *,
    snapshots: list[EntitySnapshot],
) -> dict[str, EntitySnapshot]:
    """Index snapshots while rejecting ambiguous duplicate identities."""
    indexed: dict[str, EntitySnapshot] = {}
    for snapshot in snapshots:
        if snapshot.entity_key in indexed:
            raise ValueError(f"Duplicate entity key {snapshot.entity_key!r}.")
        indexed[snapshot.entity_key] = snapshot
    return indexed


def changed_fields(
    *,
    before: dict[str, JsonValue],
    after: dict[str, JsonValue],
) -> list[FieldChange]:
    """Return stable top-level field changes, keeping nested values intact."""
    changes: list[FieldChange] = []
    for field in sorted(before.keys() | after.keys()):
        before_present = field in before
        after_present = field in after
        before_value = before.get(field)
        after_value = after.get(field)
        if before_present == after_present and before_value == after_value:
            continue
        changes.append(
            FieldChange(
                field=field,
                before=ChangeValue(present=before_present, value=before_value),
                after=ChangeValue(present=after_present, value=after_value),
            ),
        )
    return changes


def entity_change_for_create(*, snapshot: EntitySnapshot) -> EntityChangeDraft:
    """Describe every top-level value on a newly observed entity."""
    return EntityChangeDraft(
        entity_key=snapshot.entity_key,
        entity_label=snapshot.entity_label,
        kind=ChangeKind.CREATED,
        fields=[
            FieldChange(
                field=field,
                before=ChangeValue(present=False, value=None),
                after=ChangeValue(present=True, value=value),
            )
            for field, value in sorted(snapshot.data.items())
        ],
    )


def entity_change_for_delete(*, snapshot: EntitySnapshot) -> EntityChangeDraft:
    """Describe every top-level value on a removed entity."""
    return EntityChangeDraft(
        entity_key=snapshot.entity_key,
        entity_label=snapshot.entity_label,
        kind=ChangeKind.DELETED,
        fields=[
            FieldChange(
                field=field,
                before=ChangeValue(present=True, value=value),
                after=ChangeValue(present=False, value=None),
            )
            for field, value in sorted(snapshot.data.items())
        ],
    )
